services:
  postgres:
    image: postgres:16-alpine
    container_name: cms-zoco-postgres
    environment:
      POSTGRES_USER: zoco
      POSTGRES_PASSWORD: zoco123
      POSTGRES_DB: cms_zoco
    ports:
      - "5432:5432"
    volumes:
      - cms_zoco_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zoco -d cms_zoco"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cms_zoco_data:
